# Generated by Django 4.0.4 on 2022-04-16 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeprice',
            name='bathrooms',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homeprice',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f59ab791-a911-4238-9b3a-98bbb07e9572'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b24e9fc-6afb-41e5-a6c8-de8c7fff2e1b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
