# Generated by Django 4.0.4 on 2022-04-16 15:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_homeprice_bathrooms_alter_homeprice_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeprice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
