# Generated by Django 4.0.4 on 2022-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_homeprice_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
